### ISSUE TITLE
Failure to dock into systray

### ISSUE THREAD

**Issue by nannerpusser** [gtkevemon/gtkevemon#67]
Just a heads up, but I'm unable to minimize or close to the tray in Cinnamon 3.4.6-1 running on Vanilla Arch (4.12.13-1-ARCH x86_64). I've had to use AllTray for a few months since install, but no big deal. 

Is this a GTK/Cinnamon issue or is it the app? I'm under the assumption this has been documented and discussed with how popular Cinnamon is and the GTK3 switchover bugs from before, but if this is brand new I will gather any logs or output or screenshots as requested. 

Edit: I just realized I forgot half the issue. I CAN minimize GtkEveMon and the dock icon appears and mouse/menu functionality is fine, however the app remains in my taskbar. I've seen this behavior before with other apps and Cinnamon's inability to "force" an app to skip the taskbar, which is why I have a feeling this is a local/Cinnamon/GTK issue.

Also, I'm running the AUR build of GtkEveMon (gtkevemon-git r239.c8e4682-1)

This was a notorious issue with Steam and here's the old "Close to Tray" thread for reference. An env variable like STEAM_FRAME_FORCE_CLOSE for GtkEveMon would be epic, but I know that's a longshot:
https://github.com/ValveSoftware/steam-for-linux/issues/1025

**Comment by simonfuhrmann** [comment]
Hi. I remember I wasted quite some time getting the tray feature to work because for some reason, it's a tricky topic. It worked well for a long time, then users had issues, I submitted fixes, and now it seems to come back. I don't know if this is a glitch with Cinnamon (but I doubt it), it's probably how GtkEveMon issues the instructions. 

Since it is almost impossible to fix this without having the exact same setup, would you mind trying to play around with it and get it working? The code for handling tray is here:
https://github.com/gtkevemon/gtkevemon/blob/master/src/gui/maingui.cc#L496
and the following functions in that file.

**Comment by nannerpusser** [comment]
So I tried a couple things, including skipping the taskbar completely in any state (I liked it but I know most wouldn't) but in the end all I had to do was uncomment your written code beginning here:

https://github.com/nannerpusser/gtkevemon/blob/afd8f668c2bae04e60c59768a0b1c9fdc470ba45/src/gui/maingui.cc#L508

I know exactly nothing about C++ and I've never forked + modified anything public on Git, so I apologize if the changes screw with anything. I've forked and committed it to my own branch, but clearly this takes three seconds to alter and I could train a small animal to do it, so perhaps just leaving the note for future users with Cinnamon is enough.
